FROM alpine:latest

RUN apk update
RUN apk add --no-cache curl freetype gcompat libxext libxi libxrender libxtst procps unzip
RUN apk add --no-cache ca-certificates git gnupg openssh sudo unzip wget
RUN apk add --no-cache build-base cmake
RUN apk add --no-cache gdb valgrind
RUN apk add --no-cache readline-dev
